# Generated by Django 3.0.5 on 2020-05-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelist',
            name='file',
            field=models.FileField(upload_to='', verbose_name='Файл'),
        ),
    ]
